# Generated by Django 4.2.17 on 2025-07-23 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                ("amount", models.DecimalField(decimal_places=8, max_digits=19)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("crypto", "Crypto"),
                            ("stock", "Stock"),
                            ("cash", "Cash"),
                            ("other", "Other"),
                        ],
                        default="crypto",
                        max_length=10,
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NetWorthSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("net_worth", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["date"], "unique_together": {("user", "date")},},
        ),
    ]
