# Generated by Django 4.2.17 on 2025-07-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networthsnapshot", name="date", field=models.DateField(),
        ),
    ]
