# Generated by Django 4.2.17 on 2025-07-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="type",
            field=models.CharField(
                choices=[
                    ("crypto", "Crypto"),
                    ("stock", "Stock"),
                    ("cash", "Cash"),
                    ("real_estate", "Real Estate"),
                    ("other", "Other"),
                ],
                default="crypto",
                max_length=20,
            ),
        ),
    ]
