# Generated by Django 5.0.2 on 2025-07-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
