# Generated by Django 4.2.17 on 2025-07-23 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_asset_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="networthsnapshot",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
