# Generated by Django 5.0.2 on 2025-07-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_asset_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="type",
            field=models.CharField(
                choices=[("crypto", "Crypto"), ("stock", "Stock")],
                default="crypto",
                max_length=10,
            ),
        ),
    ]
