# Generated by Django 5.0.2 on 2026-03-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_asset_type_brazilstock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="type",
            field=models.CharField(
                choices=[
                    ("crypto", "Crypto"),
                    ("stock", "Stock"),
                    ("cash", "Cash"),
                    ("real_estate", "Real Estate"),
                    ("vehicle", "Vehicle"),
                    ("other", "Other"),
                ],
                default="crypto",
                max_length=20,
            ),
        ),
    ]
