# Generated by Django 5.0.2 on 2025-07-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_asset_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='currency',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('crypto', 'Crypto'), ('stock', 'Stock'), ('cash', 'Cash')], default='crypto', max_length=10),
        ),
    ]
