# Generated by Django 5.0.2 on 2025-07-19 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_asset_currency_alter_asset_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="type",
            field=models.CharField(
                choices=[
                    ("crypto", "Crypto"),
                    ("stock", "Stock"),
                    ("cash", "Cash"),
                    ("other", "Other"),
                ],
                default="crypto",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="NetWorthSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("net_worth", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["date"], "unique_together": {("user", "date")},},
        ),
    ]
